# Configuration for NovatoBar Plugin

# Remaining time in seconds when the server stops
remainingTime: 0

# Original time set for the timer in seconds
originalTime: 0

# Indicates if the timer has ended
timerEnded: false

# Indicates if the timer is currently active
timerActive: false


permissions:
  timer:
    start: "novato.timer.start"
    set: "novato.timer.set"
    stop: "novato.timer.stop"
    config: "novato.timer.config"