name: NovatoBar
main: org.novatoBar.NovatoBar
version: 1.1-SNAPSHOT
commands:
  timer:
    description: Manage the timer boss bar
    usage: "/timer <start | set | stop> [seconds], Alias /t "
    aliases: [t]
